language: php
sudo: required
dist: precise

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    include:
        - env: ADAPTER=src/Adapter/Apc

addons:
    apt:
        packages:
            - parallel

services:
    - redis
    - memcached

env:
  global:
    - MONGODB_HOST="localhost:27017"
    - MONGODB_DATABASE="test"
    - MONGODB_COLLECTION="cache"
    - INTEGRATION_TEST_VERSION="0.7.0"

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - if [ -f build/php/$TRAVIS_PHP_VERSION.sh]; then ./build/php/$TRAVIS_PHP_VERSION.sh; fi
    - if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then ./build/php/5.x.sh; fi
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then ./build/php/7.x.sh; fi
    - ./build/php/all.sh
    - travis_retry composer self-update

install:
    - composer require --no-update mongodb/mongodb:^1.0
    - composer require --no-update cache/integration-tests:$INTEGRATION_TEST_VERSION
    - composer install --no-interaction --prefer-source


script:
    - ./build/runTest.sh $ADAPTER

after_success:
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then codecov ; fi

notifications:
    email: false
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7b0035a70de31fa976df
