language: php
sudo: required
dist: precise

matrix:
    include:
        - php: 5.5
          env: ADAPTER=Apc
        - php: 5.6
          env: ADAPTER=Apc
        - php: 7.0
          env: ADAPTER=Apc

services:
    - redis
    - memcached

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
    - ./build/setEnvVariables.sh
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - if [ -f build/php/$TRAVIS_PHP_VERSION/$PROJECT.sh]; then ./build/php/$TRAVIS_PHP_VERSION/$PROJECT.sh; fi
    #- if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then ./build/php/5.x.sh; fi
    #- if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then ./build/php/7.x.sh; fi
    #- ./build/php/all.sh
    - travis_retry composer self-update

install:
    #- composer require --no-update mongodb/mongodb:^1.0
    - composer require --no-update cache/integration-tests:$INTEGRATION_TEST_VERSION
    - composer install --no-interaction --prefer-source


script:
    - ./build/runTest.sh $DIR$PROJECT
    - ./build/runTest.sh ./ --coverage-clover=coverage.xml

after_success:
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then codecov ; fi

notifications:
    email: false
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7b0035a70de31fa976df
